package com.riskdesk.domain.playbook.automation;

public enum PlaybookRoutingOutcome {
    PAPER_ONLY,
    ROUTED,
    ACK_PENDING,
    SKIPPED_AUTO_OFF,
    SKIPPED_BELOW_PAPER_THRESHOLD,
    SKIPPED_BELOW_LIVE_THRESHOLD,
    SKIPPED_LATE_ENTRY,
    SKIPPED_NO_PLAN,
    SKIPPED_NO_QTY,
    SKIPPED_NO_ACCOUNT,
    SKIPPED_DUPLICATE,
    SKIPPED_STALE_PRICE_SOURCE,
    SKIPPED_IBKR_DISABLED,
    SKIPPED_INSUFFICIENT_MARGIN,
    FAILED,
    FAILED_TIMEOUT,
    FAILED_BROKER_REJECT
}
