package com.riskdesk.infrastructure.quant.simulation.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity for the {@code quant_7gates_simulations} table.
 *
 * <p>The {@code id} is assigned by the application service (an in-memory
 * sequence seeded from {@code max(id)} on restart) rather than generated by
 * the database, so ids stay stable across the in-memory view and the durable
 * store. Timestamps are {@link Instant} (UTC) per the project's date/time
 * rules; exit fields are boxed so unset values persist as {@code NULL}.
 */
@Entity
@Table(name = "quant_7gates_simulations")
public class Quant7GatesSimulationEntity {

    @Id
    @Column(name = "id")
    private Long id;

    @Column(name = "instrument", nullable = false, length = 20)
    private String instrument;

    @Column(name = "direction", nullable = false, length = 10)
    private String direction;

    @Column(name = "entry_price", nullable = false)
    private double entryPrice;

    @Column(name = "stop_loss", nullable = false)
    private double stopLoss;

    @Column(name = "take_profit1", nullable = false)
    private double takeProfit1;

    @Column(name = "take_profit2", nullable = false)
    private double takeProfit2;

    @Column(name = "opened_at", nullable = false)
    private Instant openedAt;

    @Lob
    @Column(name = "entry_reason", columnDefinition = "text")
    private String entryReason;

    @Column(name = "price_source", length = 30)
    private String priceSource;

    @Column(name = "status", nullable = false, length = 30)
    private String status;

    @Column(name = "exit_price")
    private Double exitPrice;

    @Column(name = "exit_price_source", length = 30)
    private String exitPriceSource;

    @Column(name = "closed_at")
    private Instant closedAt;

    @Lob
    @Column(name = "exit_reason", columnDefinition = "text")
    private String exitReason;

    @Column(name = "pnl_points")
    private Double pnlPoints;

    @Column(name = "pnl_usd")
    private Double pnlUsd;

    protected Quant7GatesSimulationEntity() {}

    public Quant7GatesSimulationEntity(Long id) {
        this.id = id;
    }

    // ── Getters & setters ──────────────────────────────────────────────────

    public Long getId() { return id; }

    public String getInstrument() { return instrument; }
    public void setInstrument(String instrument) { this.instrument = instrument; }

    public String getDirection() { return direction; }
    public void setDirection(String direction) { this.direction = direction; }

    public double getEntryPrice() { return entryPrice; }
    public void setEntryPrice(double entryPrice) { this.entryPrice = entryPrice; }

    public double getStopLoss() { return stopLoss; }
    public void setStopLoss(double stopLoss) { this.stopLoss = stopLoss; }

    public double getTakeProfit1() { return takeProfit1; }
    public void setTakeProfit1(double takeProfit1) { this.takeProfit1 = takeProfit1; }

    public double getTakeProfit2() { return takeProfit2; }
    public void setTakeProfit2(double takeProfit2) { this.takeProfit2 = takeProfit2; }

    public Instant getOpenedAt() { return openedAt; }
    public void setOpenedAt(Instant openedAt) { this.openedAt = openedAt; }

    public String getEntryReason() { return entryReason; }
    public void setEntryReason(String entryReason) { this.entryReason = entryReason; }

    public String getPriceSource() { return priceSource; }
    public void setPriceSource(String priceSource) { this.priceSource = priceSource; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public Double getExitPrice() { return exitPrice; }
    public void setExitPrice(Double exitPrice) { this.exitPrice = exitPrice; }

    public String getExitPriceSource() { return exitPriceSource; }
    public void setExitPriceSource(String exitPriceSource) { this.exitPriceSource = exitPriceSource; }

    public Instant getClosedAt() { return closedAt; }
    public void setClosedAt(Instant closedAt) { this.closedAt = closedAt; }

    public String getExitReason() { return exitReason; }
    public void setExitReason(String exitReason) { this.exitReason = exitReason; }

    public Double getPnlPoints() { return pnlPoints; }
    public void setPnlPoints(Double pnlPoints) { this.pnlPoints = pnlPoints; }

    public Double getPnlUsd() { return pnlUsd; }
    public void setPnlUsd(Double pnlUsd) { this.pnlUsd = pnlUsd; }
}
